version: '3.7'
services:
  documentservice:
    image: onlyoffice/documentserver:5.3.1.26
    volumes:
      - /opt/onlyoffice/data:/var/www/onlyoffice/Data
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      - TZ=America/Lima
    extra_hosts:
      - owncloud.host.name:10.0.0.1
